-- use expense_tracker_db;
-- SET FOREIGN_KEY_CHECKS = 0;
--
-- TRUNCATE TABLE expense;
-- TRUNCATE TABLE category;
-- TRUNCATE TABLE user;
--
--
-- INSERT INTO  user(`id`, `name`, `email`) VALUES (1, 'jude', 'jude@gmail.com'),
-- (2, 'ehis', 'ehis@gmail.com');
--
-- INSERT INTO category(`id`, `name`) VALUES (01,'travel'),
-- (02, 'loan');
--
-- INSERT INTO exepnse(`id`, `expensedate`, `description`, `user_id`, `category_id`) VALUES (100, 'new york', '2013-05-30 38:23.085',1,01),
-- (200, 'toyota', '2013-05-30 38:23.089',2,02);
